
name: ""
description: "Henryk Paluch user pages"
url: "https://hpaluch.github.io"

# See https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902
exclude: [ "vendor", "*.sh" , "*.swp", "README.md" ]

